[package]

name = "lazysort"
version = "0.2.0"
authors = ["Ben Ashford"]
license = "MIT/Apache-2.0"
repository = "https://github.com/benashford/rust-lazysort"
description = "Lazy sorting for iterators"
readme = "README.md"

[features]
nightly = []

[dependencies]

rand = ">= 0.3, <= 0.5"
